### ISSUE TITLE
[FEATURE] Profile Page - Profile Info

### ISSUE THREAD

**Issue by ludwigschubi** [0wntech/drive#26]
This ticket depends on #25 

## User Story
As a user, I would like to see my profile, so that I can see and manage what information people can see on my profile.

## Requirements/Acceptance Criteria
A view on my profile page that includes:
* A users profile Info:
  * a users url
  * Name
  * Job
  * Bio
  * Email
  * Telephone Number

## Design
![Drive with Buttons](https://user-images.githubusercontent.com/35169452/63917721-884ade80-ca3b-11e9-826a-561c70a989cf.png)
(Edit icon can be left out for this ticket)

Figma Link: https://www.figma.com/file/XrBUjeubqoEqMyimhrjTvzEl/Untitled?node-id=140%3A219

**Comment by bejow** [comment]
@ludwigschubi What do you think about adding all profile information, since we want to give the user full control over their pod?

**Comment by ludwigschubi** [comment]
What do you mean by all? Some information that is stored within card will go into the settings page

**Comment by bejow** [comment]
e.g adress, birthday etc could be important informations.
